[package]
name = "wasmer_datetime_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
libc = "0.2.147"
wasi = "0.11.0"
